spring.application.name=service-registry
server.port=8761


#Do not register yourself as a service inside yourself.
eureka.client.register-with-eureka=false
#Do not try to fetch the list of services from another Eureka server.
eureka.client.fetch-registry=false
