spring.application.name=auth-api

server.port=8081

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

#Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/auth-db
spring.datasource.username=postgres
spring.datasource.password=postgres

#Spring security
jwt.secret.password=mySuperSecretKey12345678901234567890
jwt.expiration.time=1000000
