spring.application.name=job-api
server.port=8082

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.datasource.url=jdbc:postgresql://localhost:5432/job_db
spring.datasource.username=postgres
spring.datasource.password=postgres

jwt.secret.password=mySuperSecretKey12345678901234567890